"""added favorite club col

Revision ID: 764d47cc35a5
Revises: 337bdbeb0a1f
Create Date: 2020-05-13 08:02:20.065641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764d47cc35a5'
down_revision = '337bdbeb0a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_club', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_club')
    # ### end Alembic commands ###
